# Generated by Django 4.2.4 on 2023-09-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_women_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
