# Generated by Django 4.2.4 on 2023-09-08 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='women',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='women.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='women',
            name='slug',
            field=models.SlugField(default=0, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
